name: CI/CD Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
      
  deploy:
    name: Deploy
    runs-on: [ self-hosted, label-docker ] 
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} 
      - name: Database Data Move
        run: sudo mv /home/ec2-user/actions-runner/_work/test-docker/test-docker/database/data /home    
      - uses: actions/checkout@v3
      - name: Database Data return
        run: sudo mv /home/data /home/ec2-user/actions-runner/_work/test-docker/test-docker/database 
      - name: Docker stop
        run: docker-compose stop 
      - name: Docker remove
        run: docker-compose rm -f
      - name: Docker compose
        run: |  
         cd /home/ec2-user/actions-runner/_work/test-docker/test-docker
         docker-compose up -d
          
