name: CI/CD Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# 환경설정
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # github repository에서 checkout
      - uses: actions/checkout@v2
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}   
      - name: Docker run
        run: |
          docker-compose kill
          docker-compose rm
          docker image rm
          docker compose -f ./docker-compose.yml up
          
